/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Stream June's reply as SSE. Each frame is a JSON-encoded ChatEvent.
         */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Memory
         * @description Return a structured highlight reel of what June remembers about a user.
         *
         *     Week 2: SQLite-only. Week 4 will fan out to vector + graph stores
         *     and merge the rankings (ADR 0004).
         */
        get: operations["get_memory_memory__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Skills
         * @description Enumerate the tools June can call right now.
         */
        get: operations["list_skills_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get System Status
         * @description Report which runtime is active and whether it's actually usable.
         *
         *     Shells display a small runtime badge built from this payload, so it
         *     must be honest about misconfigurations (Ollama not running, Gemma
         *     tag not pulled, missing API key) instead of pretending everything
         *     is fine.
         */
        get: operations["get_system_status_system_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe — no brain calls, just confirms the process is up.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChatRequest
         * @description A single user turn submitted to POST /chat.
         */
        ChatRequest: {
            /**
             * User Id
             * @description Stable identifier for the user. Used as the memory partition key.
             */
            user_id: string;
            /**
             * Message
             * @description The user's message in plain text.
             */
            message: string;
            /**
             * Skill
             * @description Optional skill hint to guide the agent. Defaults to general assistant behavior.
             * @default assistant
             */
            skill: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MemoryFact
         * @description One structured row read from memory.
         */
        MemoryFact: {
            /**
             * Kind
             * @description Category of fact, e.g. 'goal', 'calendar_item', 'preference'.
             */
            kind: string;
            /**
             * Title
             * @description Short human-readable label.
             * @default
             */
            title: string;
            /**
             * Body
             * @description Longer description or detail, when present.
             * @default
             */
            body: string;
            /**
             * Metadata
             * @description Structured fields specific to this fact kind.
             */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * MemorySnapshot
         * @description Summary of what June remembers about a user.
         *
         *     Week 2 returns structured highlights from the SQLite store. Week 4
         *     will extend this with vector-recalled facts and graph neighbors.
         */
        MemorySnapshot: {
            /** User Id */
            user_id: string;
            /** Goals */
            goals?: components["schemas"]["MemoryFact"][];
            /** Open Loops */
            open_loops?: components["schemas"]["MemoryFact"][];
            /** Calendar */
            calendar?: components["schemas"]["MemoryFact"][];
            /**
             * Recent Messages
             * @description Chat messages stored for this user.
             * @default 0
             */
            recent_messages: number;
        };
        /**
         * SkillInfo
         * @description A single tool exposed to the agent.
         *
         *     Week 2 maps one-to-one onto the current LangChain tools. Week 5
         *     groups these by skill (calendar, health, research, ...) once the
         *     MCP decomposition lands.
         */
        SkillInfo: {
            /**
             * Name
             * @description Tool identifier used by the agent when calling it.
             */
            name: string;
            /**
             * Description
             * @description Human-readable description.
             * @default
             */
            description: string;
            /**
             * Category
             * @description Group label; Week 5 maps this to MCP skill server.
             * @default core
             */
            category: string;
        };
        /** SkillsResponse */
        SkillsResponse: {
            /** Skills */
            skills?: components["schemas"]["SkillInfo"][];
            /**
             * Count
             * @default 0
             */
            count: number;
        };
        /**
         * SystemStatus
         * @description What the shells need to display a honest runtime indicator.
         */
        SystemStatus: {
            /**
             * Provider
             * @description Active preset key: 'gemma' or 'gemini'.
             */
            provider: string;
            /**
             * Label
             * @description Human-readable runtime label.
             */
            label: string;
            /**
             * Model
             * @description Active model identifier.
             */
            model: string;
            /**
             * Mode
             * @description 'local' when inference stays on-device, 'api' otherwise.
             */
            mode: string;
            /**
             * Privacy Label
             * @description 'local-only' or 'api-assisted'.
             */
            privacy_label: string;
            /**
             * Base Url
             * @description Endpoint the brain is talking to.
             * @default
             */
            base_url: string;
            /**
             * Ollama Reachable
             * @description True when the configured Ollama instance responds. Only meaningful for the gemma preset.
             * @default false
             */
            ollama_reachable: boolean;
            /**
             * Ollama Has Model
             * @description True when the active Gemma tag is already pulled. Only meaningful for the gemma preset.
             * @default false
             */
            ollama_has_model: boolean;
            /**
             * Api Key Present
             * @description True when the active runtime has the credentials it needs. Only meaningful for the gemini preset.
             * @default false
             */
            api_key_present: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ChatEvent
         * @description One item in the SSE stream returned by POST /chat.
         *
         *     The wire format is one ``data:`` frame per event carrying a JSON
         *     object with this shape. ``type`` drives the UI.
         */
        ChatEvent: {
            /**
             * Type
             * @description Discriminator that determines the meaning of the payload.
             * @enum {string}
             */
            type: "token" | "tool_call" | "tool_result" | "done" | "error";
            /**
             * Content
             * @description Textual content for token and error events; empty otherwise.
             * @default
             */
            content: string;
            /**
             * Tool Name
             * @description Name of the tool for tool_call and tool_result events.
             * @default
             */
            tool_name: string;
            /**
             * Tool Args
             * @description Arguments passed to the tool for tool_call events.
             */
            tool_args?: {
                [key: string]: unknown;
            };
            /**
             * Tool Result
             * @description Serialized result returned by the tool for tool_result events.
             * @default
             */
            tool_result: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Server-Sent Events stream. See ChatEvent for the frame payload schema. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_memory_memory__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemorySnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_skills_skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsResponse"];
                };
            };
        };
    };
    get_system_status_system_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
