/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Stream June's reply as SSE. Each frame is a JSON-encoded ChatEvent.
         */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Memory
         * @description Return everything June remembers about a user, across all three stores.
         */
        get: operations["get_memory_memory__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/{user_id}/fact/{ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Memory Fact
         * @description Remove a fact by its opaque ref.
         *
         *     Supports refs returned from ``GET /memory``:
         *       - ``semantic:<fact_id>`` removes a semantic fact from vector + shadow
         *       - ``node:<node_id>`` removes a graph entity and its edges
         *       - ``edge:<src>|<dst>|<kind>`` removes a single edge
         *       - ``goal:<title>`` removes a structured goal
         *       - ``open_loop:<topic>`` removes a structured open loop
         *       - ``calendar:<title>|<date>|<time>`` removes a structured calendar item
         *       - ``journal:<id>`` removes a journal entry
         *       - ``body_metric:<date>`` removes a body metric row
         */
        delete: operations["delete_memory_fact_memory__user_id__fact__ref__delete"];
        options?: never;
        head?: never;
        /**
         * Update Memory Fact
         * @description Patch a structured fact by ref.
         *
         *     Only the SQLite ref kinds are supported (``goal:``, ``open_loop:``,
         *     ``calendar:``). Editing semantic facts or graph nodes is not yet
         *     exposed here; those have their own paths.
         *
         *     The returned ``ref`` may differ from the request ``ref`` when the
         *     primary key changed (a goal renamed, a calendar item rescheduled).
         *     Clients should use the returned ref for any subsequent edit or
         *     delete operation on the same fact.
         */
        patch: operations["update_memory_fact_memory__user_id__fact__ref__patch"];
        trace?: never;
    };
    "/memory/{user_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Memory Feedback
         * @description Record a thumbs-up / thumbs-down vote on a recalled memory.
         *
         *     The vote nudges the recall ranker for future turns:
         *       - ``up`` halves the score (lower is more relevant for distance-based hits).
         *       - ``down`` doubles the score.
         *       - ``clear`` removes the vote.
         *
         *     Voting on a fact that does not exist is allowed — the feedback row stands
         *     alone and applies the next time a hit with this ref is recalled. This
         *     keeps the API simple at the cost of orphan rows; ``clear`` always wins
         *     if the user changes their mind.
         */
        post: operations["set_memory_feedback_memory__user_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description Return the current non-secret configuration plus reachability flags.
         */
        get: operations["get_settings_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/forget-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Forget Key
         * @description Delete the Gemini key from the OS credential store and the JSON fallback.
         */
        post: operations["forget_key_settings_forget_key_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Setup Status
         * @description Report whether the active runtime is ready to serve chat requests.
         */
        get: operations["get_setup_status_setup_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply Setup
         * @description Persist the user's provider choice and verify it with a live round-trip.
         */
        post: operations["apply_setup_setup_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Skills
         * @description List every MCP skill with its current enabled state and tools.
         */
        get: operations["list_skills_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills/{key}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Toggle Skill
         * @description Enable or disable a skill.
         *
         *     Persists to ``~/Library/Application Support/June/skills.toml`` and
         *     rebuilds the agent so the next chat turn picks up the new tool set.
         */
        post: operations["toggle_skill_skills__key__toggle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get System Status
         * @description Report which runtime is active and whether it's actually usable.
         *
         *     Shells display a small runtime badge built from this payload, so it
         *     must be honest about misconfigurations (Ollama not running, Gemma
         *     tag not pulled, missing API key) instead of pretending everything
         *     is fine.
         */
        get: operations["get_system_status_system_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe — no brain calls, just confirms the process is up.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChatRequest
         * @description A single user turn submitted to POST /chat.
         */
        ChatRequest: {
            /**
             * User Id
             * @description Stable identifier for the user. Used as the memory partition key.
             */
            user_id: string;
            /**
             * Message
             * @description The user's message in plain text.
             */
            message: string;
            /**
             * Skill
             * @description Optional skill hint to guide the agent. Defaults to general assistant behavior.
             * @default assistant
             */
            skill: string;
        };
        /**
         * ForgetKeyResponse
         * @description Outcome of POST /settings/forget-key.
         */
        ForgetKeyResponse: {
            /**
             * Cleared From
             * @description Where the key actually lived. 'none' means nothing was stored.
             * @enum {string}
             */
            cleared_from: "keyring" | "file" | "none";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MemoryDeleteResponse
         * @description Result of DELETE /memory/{user_id}/fact/{ref}.
         */
        MemoryDeleteResponse: {
            /** User Id */
            user_id: string;
            /** Ref */
            ref: string;
            /** Removed */
            removed: boolean;
        };
        /**
         * MemoryFact
         * @description One structured row read from memory.
         *
         *     ``ref`` is a stable opaque string that DELETE /memory/{user}/fact/{ref}
         *     understands. It carries the source tag (``semantic:``, ``node:``,
         *     ``edge:``, ``goal:``…) so the API can route the delete to the right
         *     store without a second schema lookup.
         */
        MemoryFact: {
            /**
             * Kind
             * @description Category of fact, e.g. 'goal', 'semantic', 'entity:person'.
             */
            kind: string;
            /**
             * Title
             * @description Short human-readable label.
             * @default
             */
            title: string;
            /**
             * Body
             * @description Longer description or detail, when present.
             * @default
             */
            body: string;
            /**
             * Ref
             * @description Opaque identifier for delete/edit operations.
             * @default
             */
            ref: string;
            /**
             * Metadata
             * @description Structured fields specific to this fact kind.
             */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * MemoryFeedbackRequest
         * @description Body of POST /memory/{user_id}/feedback.
         *
         *     ``vote`` is one of:
         *       - ``"up"`` — this memory was useful; rank it higher next time.
         *       - ``"down"`` — this memory was wrong or irrelevant; rank it lower.
         *       - ``"clear"`` — remove any prior vote on this ref.
         */
        MemoryFeedbackRequest: {
            /**
             * Ref
             * @description Opaque memory identifier (same scheme as /memory).
             */
            ref: string;
            /**
             * Vote
             * @description One of "up", "down", or "clear".
             */
            vote: string;
        };
        /**
         * MemoryFeedbackResponse
         * @description Result of POST /memory/{user_id}/feedback.
         */
        MemoryFeedbackResponse: {
            /** User Id */
            user_id: string;
            /** Ref */
            ref: string;
            /**
             * Vote
             * @description "up", "down", or "" when cleared / unrecorded.
             * @default
             */
            vote: string;
        };
        /**
         * MemorySnapshot
         * @description Summary of what June remembers about a user.
         *
         *     The SQLite structured tables, the vector semantic store, and the
         *     knowledge graph are all represented. UI can show them grouped or
         *     merged in a timeline.
         */
        MemorySnapshot: {
            /** User Id */
            user_id: string;
            /** Goals */
            goals?: components["schemas"]["MemoryFact"][];
            /** Open Loops */
            open_loops?: components["schemas"]["MemoryFact"][];
            /** Calendar */
            calendar?: components["schemas"]["MemoryFact"][];
            /**
             * Journal
             * @description Recent journal entries written by the user or by the daily skill.
             */
            journal?: components["schemas"]["MemoryFact"][];
            /**
             * Body Metrics
             * @description Body metrics recorded by the health skill (one row per day).
             */
            body_metrics?: components["schemas"]["MemoryFact"][];
            /**
             * Semantic Facts
             * @description Facts extracted from conversation and embedded for semantic recall.
             */
            semantic_facts?: components["schemas"]["MemoryFact"][];
            /**
             * Entities
             * @description People, places, projects and concepts June has mapped for this user.
             */
            entities?: components["schemas"]["MemoryFact"][];
            /**
             * Recent Messages
             * @description Chat messages stored for this user.
             * @default 0
             */
            recent_messages: number;
        };
        /**
         * MemoryUpdateRequest
         * @description Body of PATCH /memory/{user_id}/fact/{ref}.
         *
         *     All fields are optional strings; missing keys preserve current values.
         *     The set of accepted keys depends on the ref kind:
         *       - goal: title, category, target_date, next_step, status
         *       - open_loop: topic, next_step, due_date, status
         *       - calendar: title, date, time, details, status, source
         */
        MemoryUpdateRequest: {
            /**
             * Fields
             * @description Map of field name to new value. Unset fields keep current values.
             */
            fields?: {
                [key: string]: string;
            };
        };
        /**
         * MemoryUpdateResponse
         * @description Result of PATCH /memory/{user_id}/fact/{ref}.
         *
         *     ``ref`` may be a *new* opaque identifier when the primary key changed
         *     (e.g. a goal renamed). Clients should use the returned ref for any
         *     subsequent edit/delete on this fact.
         */
        MemoryUpdateResponse: {
            /** User Id */
            user_id: string;
            /** Ref */
            ref: string;
            /** Updated */
            updated: boolean;
            fact?: components["schemas"]["MemoryFact"] | null;
        };
        /**
         * SettingsView
         * @description Non-secret snapshot of the active configuration.
         */
        SettingsView: {
            /**
             * Provider
             * @description Active preset key ('gemma' or 'gemini').
             */
            provider: string;
            /**
             * Model
             * @description Active model identifier.
             */
            model: string;
            /**
             * Gemma Model
             * @description Persisted Gemma tag override, if any.
             * @default
             */
            gemma_model: string;
            /**
             * Gemini Model
             * @description Persisted Gemini model override, if any.
             * @default
             */
            gemini_model: string;
            /**
             * Ollama Base Url
             * @description Override for the Ollama endpoint, if any.
             * @default
             */
            ollama_base_url: string;
            /**
             * Ollama Reachable
             * @description Gemma preset only.
             * @default false
             */
            ollama_reachable: boolean;
            /**
             * Ollama Has Model
             * @description Gemma preset only.
             * @default false
             */
            ollama_has_model: boolean;
            /**
             * Api Key Present
             * @description Gemini preset only.
             * @default false
             */
            api_key_present: boolean;
            /**
             * Key Storage
             * @description Where the Gemini key is stored. 'keyring' means the OS credential store, 'file' means the 0600 config.json fallback, 'none' means no key is set.
             * @enum {string}
             */
            key_storage: "keyring" | "file" | "none";
            /**
             * Key Storage Label
             * @description Human-readable storage label for the settings UI.
             */
            key_storage_label: string;
        };
        /**
         * SetupApplyRequest
         * @description User's provider pick from the /setup screen.
         */
        SetupApplyRequest: {
            /**
             * Provider
             * @description Which runtime to activate.
             * @enum {string}
             */
            provider: "gemma" | "gemini";
            /**
             * Gemini Api Key
             * @description Required when provider is 'gemini'. Stored in config.json with mode 0600 until native credential storage lands.
             */
            gemini_api_key?: string | null;
            /**
             * Gemma Model
             * @description Ollama tag override. Defaults to the preset's default (gemma4:e4b).
             */
            gemma_model?: string | null;
            /**
             * Gemini Model
             * @description Gemini model override. Defaults to gemini-2.0-flash.
             */
            gemini_model?: string | null;
        };
        /**
         * SetupApplyResponse
         * @description Result of a setup attempt, including a verification round-trip.
         */
        SetupApplyResponse: {
            /**
             * Ok
             * @description True when the chosen provider successfully produced a token.
             */
            ok: boolean;
            /**
             * Provider
             * @description The preset that was applied.
             */
            provider: string;
            /**
             * Model
             * @description The model the provider is configured to use.
             */
            model: string;
            /**
             * Verified
             * @description True when a one-shot request to the provider returned a response.
             */
            verified: boolean;
            /**
             * Message
             * @description Short, human-readable status. Empty on clean success.
             * @default
             */
            message: string;
            /**
             * Hint
             * @description When ok is false, a specific actionable hint (e.g. 'Ollama not running').
             * @default
             */
            hint: string;
        };
        /**
         * SetupStatus
         * @description Snapshot used by the UI to decide whether to show /setup or /chat.
         */
        SetupStatus: {
            /**
             * Is Configured
             * @description True once the active provider has everything it needs to run: Ollama reachable with the Gemma tag pulled, or a Gemini API key present.
             */
            is_configured: boolean;
            /**
             * Provider
             * @description Active preset key ('gemma' or 'gemini'), or empty when no choice has been persisted.
             * @default
             */
            provider: string;
            /**
             * Model
             * @description Active model identifier, if any.
             * @default
             */
            model: string;
            /**
             * Ollama Reachable
             * @description Gemma preset only.
             * @default false
             */
            ollama_reachable: boolean;
            /**
             * Ollama Has Model
             * @description Gemma preset only.
             * @default false
             */
            ollama_has_model: boolean;
            /**
             * Api Key Present
             * @description Gemini preset only.
             * @default false
             */
            api_key_present: boolean;
        };
        /**
         * SkillInfo
         * @description One MCP skill server with its current lifecycle state.
         */
        SkillInfo: {
            /**
             * Key
             * @description Stable skill id, e.g. 'calendar' or 'research'.
             */
            key: string;
            /**
             * Description
             * @description What the skill does.
             * @default
             */
            description: string;
            /**
             * Enabled
             * @description Manifest toggle state.
             * @default true
             */
            enabled: boolean;
            /**
             * Status
             * @description Lifecycle state: stopped, starting, running, crashed, or disabled.
             * @default stopped
             */
            status: string;
            /**
             * Error
             * @description Last error message when status is 'crashed', empty otherwise.
             * @default
             */
            error: string;
            /**
             * Tools
             * @description Tools this skill contributes to the agent when running.
             */
            tools?: components["schemas"]["SkillToolInfo"][];
        };
        /**
         * SkillToggleRequest
         * @description POST /skills/{key}/toggle body.
         */
        SkillToggleRequest: {
            /**
             * Enabled
             * @description New enabled state.
             */
            enabled: boolean;
        };
        /**
         * SkillToggleResponse
         * @description Result of a toggle — callers refresh their UI from this.
         */
        SkillToggleResponse: {
            /** Key */
            key: string;
            /** Enabled */
            enabled: boolean;
            /** Status */
            status: string;
            /**
             * Error
             * @default
             */
            error: string;
        };
        /**
         * SkillToolInfo
         * @description A single tool inside a skill — shown under the skill in the UI.
         */
        SkillToolInfo: {
            /**
             * Name
             * @description Tool identifier the agent uses to call it.
             */
            name: string;
            /**
             * Description
             * @description Human-readable description.
             * @default
             */
            description: string;
        };
        /**
         * SkillsResponse
         * @description GET /skills payload.
         */
        SkillsResponse: {
            /** Skills */
            skills?: components["schemas"]["SkillInfo"][];
            /**
             * Count
             * @default 0
             */
            count: number;
        };
        /**
         * SystemStatus
         * @description What the shells need to display a honest runtime indicator.
         */
        SystemStatus: {
            /**
             * Provider
             * @description Active preset key: 'gemma' or 'gemini'.
             */
            provider: string;
            /**
             * Label
             * @description Human-readable runtime label.
             */
            label: string;
            /**
             * Model
             * @description Active model identifier.
             */
            model: string;
            /**
             * Mode
             * @description 'local' when inference stays on-device, 'api' otherwise.
             */
            mode: string;
            /**
             * Privacy Label
             * @description 'local-only' or 'api-assisted'.
             */
            privacy_label: string;
            /**
             * Base Url
             * @description Endpoint the brain is talking to.
             * @default
             */
            base_url: string;
            /**
             * Ollama Reachable
             * @description True when the configured Ollama instance responds. Only meaningful for the gemma preset.
             * @default false
             */
            ollama_reachable: boolean;
            /**
             * Ollama Has Model
             * @description True when the active Gemma tag is already pulled. Only meaningful for the gemma preset.
             * @default false
             */
            ollama_has_model: boolean;
            /**
             * Api Key Present
             * @description True when the active runtime has the credentials it needs. Only meaningful for the gemini preset.
             * @default false
             */
            api_key_present: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * RecallHit
         * @description One memory June drew on while answering this turn.
         *
         *     Carries the same ``ref`` shape used by ``/memory``, so a UI rendering
         *     these can deep-link to the source: ``semantic:<id>``, ``node:<id>``,
         *     ``goal:<title>``, etc.
         */
        RecallHit: {
            /**
             * Ref
             * @description Stable identifier; resolves in /memory.
             * @default
             */
            ref: string;
            /**
             * Text
             * @description Human-readable snippet that was injected.
             * @default
             */
            text: string;
            /**
             * Source
             * @description Which store the hit came from: 'vector', 'graph', or 'sqlite'.
             * @default
             */
            source: string;
            /**
             * Kind
             * @description Sub-type for filtering / iconography.
             * @default
             */
            kind: string;
            /**
             * Score
             * @description Loose relevance score. Lower is more relevant for distance-based sources.
             * @default null
             */
            score: number | null;
        };
        /**
         * ChatEvent
         * @description One item in the SSE stream returned by POST /chat.
         *
         *     The wire format is one ``data:`` frame per event carrying a JSON
         *     object with this shape. ``type`` drives the UI.
         */
        ChatEvent: {
            /**
             * Type
             * @description Discriminator that determines the meaning of the payload.
             * @enum {string}
             */
            type: "token" | "tool_call" | "tool_result" | "recall" | "done" | "error";
            /**
             * Content
             * @description Textual content for token and error events; empty otherwise.
             * @default
             */
            content: string;
            /**
             * Tool Name
             * @description Name of the tool for tool_call and tool_result events.
             * @default
             */
            tool_name: string;
            /**
             * Tool Args
             * @description Arguments passed to the tool for tool_call events.
             */
            tool_args?: {
                [key: string]: unknown;
            };
            /**
             * Tool Result
             * @description Serialized result returned by the tool for tool_result events.
             * @default
             */
            tool_result: string;
            /**
             * Recall Hits
             * @description Memories June drew on this turn. Emitted once, before the first token, so the UI can render a 'memories used' affordance per assistant message.
             */
            recall_hits?: components["schemas"]["RecallHit"][];
            $defs: {
                /**
                 * RecallHit
                 * @description One memory June drew on while answering this turn.
                 *
                 *     Carries the same ``ref`` shape used by ``/memory``, so a UI rendering
                 *     these can deep-link to the source: ``semantic:<id>``, ``node:<id>``,
                 *     ``goal:<title>``, etc.
                 */
                RecallHit: {
                    /**
                     * Ref
                     * @description Stable identifier; resolves in /memory.
                     * @default
                     */
                    ref: string;
                    /**
                     * Text
                     * @description Human-readable snippet that was injected.
                     * @default
                     */
                    text: string;
                    /**
                     * Source
                     * @description Which store the hit came from: 'vector', 'graph', or 'sqlite'.
                     * @default
                     */
                    source: string;
                    /**
                     * Kind
                     * @description Sub-type for filtering / iconography.
                     * @default
                     */
                    kind: string;
                    /**
                     * Score
                     * @description Loose relevance score. Lower is more relevant for distance-based sources.
                     * @default null
                     */
                    score: number | null;
                };
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Server-Sent Events stream. See ChatEvent for the frame payload schema. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_memory_memory__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemorySnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_memory_fact_memory__user_id__fact__ref__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_memory_fact_memory__user_id__fact__ref__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                ref: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_memory_feedback_memory__user_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryFeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryFeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsView"];
                };
            };
        };
    };
    forget_key_settings_forget_key_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForgetKeyResponse"];
                };
            };
        };
    };
    get_setup_status_setup_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatus"];
                };
            };
        };
    };
    apply_setup_setup_apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupApplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupApplyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_skills_skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsResponse"];
                };
            };
        };
    };
    toggle_skill_skills__key__toggle_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillToggleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillToggleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_system_status_system_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
