"""Pydantic schemas for the June API.

These define the request/response shape on the wire and feed the
OpenAPI spec that tools/codegen.sh converts to TypeScript for the UI.
"""

from .chat import ChatEvent, ChatHistory, ChatHistoryMessage, ChatRequest, RecallHit
from .home import HomeHoldings, NextDeadlineView
from .memory import (
    ForgottenListResponse,
    ForgottenMemory,
    MemoryDeleteResponse,
    MemoryFact,
    MemoryFeedbackRequest,
    MemoryFeedbackResponse,
    MemoryPurgeResponse,
    MemoryRestoreRequest,
    MemoryRestoreResponse,
    MemorySnapshot,
    MemoryStats,
    MemoryStoreCount,
    MemoryUpdateRequest,
    MemoryUpdateResponse,
    MemoryWriteRequest,
    MemoryWriteResponse,
)
from .settings import (
    ForgetKeyResponse,
    PrivacyDial,
    PrivacyDialUpdateRequest,
    PrivacyDialUpdateResponse,
    SettingsView,
)
from .setup import SetupApplyRequest, SetupApplyResponse, SetupStatus
from .silence import (
    SurfacingDecisionView,
    SurfacingDrainResponse,
    SurfacingFeedbackRequest,
    SurfacingFeedbackResponse,
    SurfacingPageResponse,
)
from .skills import (
    RegistryEntry,
    RegistryInstallResponse,
    RegistryInstallSpec,
    RegistryResponse,
    RegistryUninstallResponse,
    SkillInfo,
    SkillScopeDrift,
    SkillsResponse,
    SkillToggleRequest,
    SkillToggleResponse,
    SkillToolInfo,
    SkillToolInvokeRequest,
    SkillToolInvokeResponse,
    SkillToolToggleRequest,
    SkillToolToggleResponse,
    SkillWriteRecord,
    SkillWritesResponse,
)
from .system import (
    ActivityEntryView,
    ActivityResponse,
    CapabilityProfileView,
    EntitlementView,
    LedgerEntryView,
    LedgerPageResponse,
    LedgerSummary,
    LedgerVerifyResponse,
    SystemStatus,
    TraceEventView,
    TraceListResponse,
    TraceSummary,
    TurnTraceView,
)
from .tasks import (
    TaskApproveRequest,
    TaskCreateRequest,
    TaskDeleteResponse,
    TaskEventFrame,
    TaskListResponse,
    TaskPatchRequest,
    TaskStepView,
    TaskView,
)

__all__ = [
    "ChatEvent",
    "ChatHistory",
    "ChatHistoryMessage",
    "ChatRequest",
    "RecallHit",
    "HomeHoldings",
    "NextDeadlineView",
    "ForgottenListResponse",
    "ForgottenMemory",
    "MemoryDeleteResponse",
    "MemoryFact",
    "MemoryFeedbackRequest",
    "MemoryFeedbackResponse",
    "MemoryPurgeResponse",
    "MemoryRestoreRequest",
    "MemoryRestoreResponse",
    "MemorySnapshot",
    "MemoryStats",
    "MemoryStoreCount",
    "MemoryUpdateRequest",
    "MemoryUpdateResponse",
    "MemoryWriteRequest",
    "MemoryWriteResponse",
    "SettingsView",
    "ForgetKeyResponse",
    "PrivacyDial",
    "PrivacyDialUpdateRequest",
    "PrivacyDialUpdateResponse",
    "SetupApplyRequest",
    "SetupApplyResponse",
    "SetupStatus",
    "SkillInfo",
    "SkillScopeDrift",
    "SkillsResponse",
    "SkillToggleRequest",
    "SkillToggleResponse",
    "SkillToolInfo",
    "SkillToolInvokeRequest",
    "SkillToolInvokeResponse",
    "SkillToolToggleRequest",
    "SkillToolToggleResponse",
    "SkillWriteRecord",
    "SkillWritesResponse",
    "RegistryEntry",
    "RegistryInstallResponse",
    "RegistryInstallSpec",
    "RegistryResponse",
    "RegistryUninstallResponse",
    "CapabilityProfileView",
    "EntitlementView",
    "SystemStatus",
    "ActivityEntryView",
    "ActivityResponse",
    "LedgerEntryView",
    "LedgerPageResponse",
    "LedgerSummary",
    "LedgerVerifyResponse",
    "TraceEventView",
    "TraceListResponse",
    "TraceSummary",
    "TurnTraceView",
    "SurfacingDecisionView",
    "SurfacingDrainResponse",
    "SurfacingFeedbackRequest",
    "SurfacingFeedbackResponse",
    "SurfacingPageResponse",
    "TaskApproveRequest",
    "TaskCreateRequest",
    "TaskDeleteResponse",
    "TaskEventFrame",
    "TaskListResponse",
    "TaskPatchRequest",
    "TaskStepView",
    "TaskView",
]
